# Generated by Django 3.0.6 on 2020-06-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='describtion',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.ManyToManyField(to='users.Status'),
        ),
    ]
