# Generated by Django 3.0.6 on 2020-06-20 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200613_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='plan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular patient for every profile', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subscribe',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
