# Generated by Django 3.0.6 on 2020-06-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200604_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='jazeera.jpg', upload_to='profile_pics'),
        ),
    ]
