# Generated by Django 3.0.6 on 2020-06-20 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200620_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='plan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for every particular patient for every profile', primary_key=True, serialize=False),
        ),
    ]
