# Generated by Django 3.1 on 2020-09-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200912_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user1',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user2',
            new_name='patient',
        ),
    ]
