# Generated by Django 3.0.6 on 2020-06-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='doctor',
            new_name='user',
        ),
    ]
