# Generated by Django 3.0.6 on 2020-06-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_blog_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pricingservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=250)),
                ('price_service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.Pricing')),
            ],
        ),
    ]
