# Generated by Django 3.0.6 on 2020-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_pricing_price_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='price_service',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
