# Generated by Django 3.0.6 on 2020-06-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_pricing_price_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='price_service',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='pricingservice',
            old_name='price_service',
            new_name='pricing',
        ),
    ]
